version: '3.7'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dontcallme
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_pass
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - webnet
  adminer:
    image: adminer
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
  tomcat:
    image: tomcat
    depends_on:
      - mysql
      - adminer
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/dontcallme?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: example_db_user
      JDBC_PASS: example_db_pass
#      JAVA_OPTS: -CLASSPATH=/usr/local/tomcat/webapps/build/classes
    volumes:
      - "./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml"
      - "./tomcat/bin/catalina.sh:/usr/local/tomcat/bin/catalina.sh"
      - "./tomcat/logs:/usr/local/tomcat/logs"
      - "./tomcat/webapps:/usr/local/tomcat/webapps"
    restart: always
    ports:
     - "8081:8081"
    networks:
      - webnet
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
# cause delay over
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
# only 8080 port support
#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - "8079:8079"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - webnet

networks:
  webnet: