grafana:
  image: grafana/grafana
  ports:
    - 0.0.0.0:3000:3000
  depends_on:
    - mysql
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.role == manager

cadvisor:
  image: google/cadvisor
  hostname: '{{.Node.Hostname}}'
  command: -logtostderr -docker_only -storage_driver=mysql
    -storage_driver_db=cadvisor -storage_driver_host=mysql:3306
    -storage_driver_buffer_duration=5s
  ports:
    - 8081:8081
  depends_on:
    - influx
  deploy:
    mode: global



## ..?? How to use.. with docker-compose
gradle:
  image: gradle:5.6.3-jdk11
  volumes:
    - ./:/home/gradle/project
  user: gradle
  working_dir: /home/gradle/project
  restart: always
  networks:
    - webnet
node:
  image: node:12
  command: npm start
  working_dir: /home/node/app
  volumes:
    - ./:/home/node/app
  restart: always
  expose:
    # server port
    - 8081
  networks:
    - webnet